wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: huggingface
    huggingface_version: 2.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    start_time: 1643484095
    t:
      1:
      - 1
      - 3
      - 5
      - 11
      4: 3.7.4
      5: 0.12.5
      6: 2.5.1
      8:
      - 5
